### ISSUE TITLE
Create model with null=True for Listield doesn't work

### ISSUE THREAD

**Issue by ikreb7** [django-ldapdb/django-ldapdb#110]
Hello,

i want to create a model with a ListField, but don't define the ListField with a value yet. Here an example:

    class LdapGroup(ldapdb.models.Model):
    """ Class for representing an LDAP group entry. """

    base_dn = "ou=groups,dc=nodomain,dc=org"
    object_classes = ['extensibleObject', 'groupOfNames', 'top']

    cn = CharField(db_column='cn', max_length=200, primary_key=True)
    status = IntegerField(db_column='status', unique=True)    
    member = ListField(db_column='member', null=True)

and I want create for example:

    LdapGroup.objects.create(name='test', status=1)

But I get this error message:
    {'info': "object class 'groupOfNames' requires attribute 'member'", 'desc': 'Object class violation'}

**Comment by rbarrois** [comment]
Hi,

This is due to your underlying LDAP schema.

As stated in the [``core.schema``](https://tools.ietf.org/html/rfc2256#section-7.10), ``groupOfNames`` must have a ``member``:
```
# /etc/openldap/schema/core.schema
objectclass ( 2.5.6.9 NAME 'groupOfNames'
        DESC 'RFC2256: a group of names (DNs)'
        SUP top STRUCTURAL
        MUST ( member $ cn )
        MAY ( businessCategory $ seeAlso $ owner $ ou $ o $ description ) )
```

You cannot create a group without adding a member (you might want to either use a custom schema, or use another structure).
