### ISSUE TITLE
Tests do not complete

### ISSUE THREAD

**Issue by edushare-at** [django-ldapdb/django-ldapdb#142]
Downloading the current commit 7dd88e68d356ed6e6ac9e4f9a92b3533fa668e7b I found that `make test`does not complete successfully:

    volatildap.server.PathError: Unable to locate file core.schema; tried ['/etc/ldap/schema', '/etc/openldap/schema', '/usr/local/openldap/schema']

**Comment by rhoerbe** [comment]
Details: Centos 7.4, Python 3.4, log file attached
[ldapdb_maketest.log](https://github.com/django-ldapdb/django-ldapdb/files/1836446/ldapdb_maketest.log)

**Comment by rbarrois** [comment]
You need to have openldap installed, and its schema files.

Can you check with your package manager where it installs the "core.schema" file?

**Comment by rhoerbe** [comment]
OK, got it. 

I documented the required dependencies for a working installation on CentOS7 with a Dockerfile:
https://github.com/rhoerbe/d-django-ldapdb

Any interest in including this in the project?

**Comment by rbarrois** [comment]
Hi,

I'm not sure how your project could be integrated?

I can think of 2 options:
* Modify the test environment or volatildap to be able to run with a "volatile LDAP in a docker"
* Document where the schema files get installed under CentOS7, and either add their path to volatildap default or allow some override here.

**Comment by rhoerbe** [comment]
My problem was that I installed openldap-devel assuming that this included the schema files. Actually the root cause was not spending time on it :-(

But the dependencies are more complex than openldap-servers, -clients and -headers, like the broken installation fo pyroma. Therefore I think that a testable Dockerfile would be a good documentation for dependiences.

Testing Dockerfile would only require one command once docker is available, like `docker build -t djangoldapdb/djangoldapdb .`

The key point is the CI-suite. Using Travis CI I have been using automated Docker tests. It is quite straigtforward to setup, free for OSS and integrated into github.

**Comment by rbarrois** [comment]
Hi!

I'm afraid that I have too little time available to maintain this project; I wouldn't be able to keep that docker image up-to-date :(

However, the required setup (for Debian) is documented in ``.travis.yml`` (for the system part) and in ``tox.ini`` (for Python).

Thanks for your help ;)
