### ISSUE TITLE
{'info': 'unique_modify() got null op.orm_modlist', 'desc': 'Invalid syntax'}

### ISSUE THREAD

**Issue by peppelinux** [django-ldapdb/django-ldapdb#153]
It raises if I click on SAVE AND CONTINUE, in model admin, without any changes on fields.
If I change some fields it works without any error.

context:
Django 2, django-ldap master branch from git

**Comment by peppelinux** [comment]
Fixed in PR https://github.com/django-ldapdb/django-ldapdb/pull/152

I Close this, I hope that you'll enjoy my PR and merge in your master branch the changes I've done.

**Comment by peppelinux** [comment]
Hi @rbarrois, have you a vision about how to solve this issue?
I can code but I do not want to waste time to an approach that could sound wrong to you.

What you think we should do in terms of design to fix this?
My approach in PR https://github.com/django-ldapdb/django-ldapdb/pull/152 works but is not enough

**Comment by rbarrois** [comment]
@peppelinux this should be fixed now; let me know if you still see the issue.

**Comment by peppelinux** [comment]
Yes, it's fixed with that code, I wrote it almost a month ago and I'm wondering why you have not accepted my PR but you used the same code.  I'm widening my eyes :)

There are also some other questions and purpose regarding this beautiful project, can you accept community contributions and in which terms?

**Comment by rbarrois** [comment]
@peppelinux Thanks for the feedback :)

I'm totally open to contributions from the community, whatever their form (code, bug reports, documentation, etc.) — which you've already helped with :smiley_cat: 

Regarding code contributions, I'm sorry I didn't merge your PR without any explanation, I didn't want to seem rude :crying_cat_face:
I didn't merge it directly for a couple of reasons: the main one was that I was going using the EuroPython sprints session to go through the backlog of issues, trying to fix as many as possible — and didn't take enough time to review all suggested options; the other reason is that your PR mixes lots of different things, which makes it much harder to review for me.

In order to make it easier to get community contributions in, I do intend to write a "contribution guide" soonish, which would make it clearer how best to contribute code to the project — in a few words, it would be: open an issue to explain the problem that needs fixing; state in the PR's subject what approach has been taken; include a test reproducing the issue that is being fixed; include a ChangeLog entry; don't mix features in the same PR.

**Comment by peppelinux** [comment]
Yes, rude is the word :)

I admit that I should rebase my commits and create separate branches for every pull requests but I went fast to put my integrations in my production environment and I didn't thought that a single PR could take so much time.

btw I'll merge your commits into my fork and, actually, only the MultiValuefield with the TextField JS autosize (js) will be merged if you agree. There are some other purposes that I did not put in my PR because of your silence and also because I dunno if they are interesting for you. They are described into PR and issues posts.

I think that this could be helpfull for the project.
Let me know if it is interesting for you:

- MultiValueField (we could also make it works like a ListField but with multiline in TextField only in AdminModel) 
https://github.com/django-ldapdb/django-ldapdb/pull/152/

- Password encoding selection menu, I use it in procduction, is well tested and omni cohomprensive of all the slapd encoding algorithms.
https://github.com/django-ldapdb/django-ldapdb/pull/46#issuecomment-406627651
https://github.com/django-ldapdb/django-ldapdb/issues/162

Let's compare our ideas, I'll rebase my PR and I'll keep all in the way that you prefer if my contributions will be taken seriously into consideration. Do you enjoy these? I'll wait for your ideas, then we'll decide what we should merge first and then I'll lfollow your indications to get thm merged in the main official branch. I would like to emprove my experience with the help of the community, I think that it could be helpfull in time.
