### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by bjoernh** [django-ldapdb/django-ldapdb#62]
Do you plan to support Python 3 in the future?
This will be a really nice feature!

**Comment by chronossc** [comment]
@bjoernh by this time you have used python3-ldap without issues?

**Comment by chronossc** [comment]
I have dig around ldapdb and ldap on python 3 and saw that using `pyldap` instead `python-ldap` and `python-ldap` `py3` branch works good for at least `mockldap`. I already suggested to `mockldap` guy to use `pyladp` because it is a fork actively maintained from python-ldap that works well on python 3.

Changing django-ldapdb to pyldap works for me for Python 2.7 and Django 1.5 to 1.8, but not for Django 1.2 to 1.4 however. Maybe is something with my tox setup but I not digged more.

So, the blocker does not exist anymore, both `pyldap` and `python-ldap` `py3` branch will work. I sugest  `pyldap`. Django itself support python 3 has few versions and guess is time to django-ldapdb move on, because it is such great app :).

I don't have time to work on migration to py 3 right now, but will try to find and if @jlaine does not start itself I will do sometime in future.

Thx for this app @jlaine !

**Comment by midnightlynx** [comment]
I think it's worth considering switching dependencies to `ldap3`, as long as you're going through everything anyways to add python 3 support.

It works for python 2 and 3, it's pure python so there's no C lib dependencies, and it seems better maintained than `python-ldap` or `pyldap`.

However, the syntax is different from `python-ldap` or `pyldap`, so it's not a minor conversion to make, and I don't really know whether or not it would play well with `mockldap`. So there's that.

**Comment by midnightlynx** [comment]
PR submitted that switches to using pyldap, along with cross-compatibility fixes to make it work with python 2 & 3

**Comment by higoramp** [comment]
@midnightlynx I'm trying to test your branch with python 3, but I'm getting the following error when saving a model:
`Exception Value: 	('expected a string in the list', 'posixGroup')`
`Exception Location: ../lib/python3.4/site-packages/ldap/ldapobject.py in _ldap_call, line 257`

Do you know what it means?

**Comment by midnightlynx** [comment]
It means I messed up on the string-to-bytes encoding somewhere in the field methods that prep data to be sent to the ldap call.

Fixing it now.

**Comment by jlaine** [comment]
Hi all, ant thoughts on stepping up to maintain django-ldapdb? As stated in #84 I would like to hand off maintenance to someone else.

**Comment by rbarrois** [comment]
django-ldapdb now supports Python3 since version 0.5.0 :wink:
